[versions]
kotlin = "2.4.20"
compose = "1.12.1"

agp = "9.4.1"
activity = "1.13.0"

spotless = "8.10.2"

[libraries]
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose" }

activity-ktx = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }

chime = { group = "software.aws.chimesdk", name = "amazon-chime-sdk", version = "0.25.5" }
chime-media = { group = "software.aws.chimesdk", name = "amazon-chime-sdk-media", version = "0.25.4" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

dokka = { id = "org.jetbrains.dokka", version = "2.2.0" }
publishing = { id = "com.vanniktech.maven.publish", version = "0.37.0" }

spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
